# Generated by Django 5.2.5 on 2025-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('party_name', models.CharField(max_length=255)),
                ('job_size', models.CharField(max_length=100)),
                ('paper', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=50)),
                ('job_details', models.TextField()),
                ('ctp', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_by', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('lami_size', models.CharField(blank=True, max_length=100, null=True)),
                ('enve_size', models.CharField(blank=True, max_length=100, null=True)),
                ('ctp_no', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lami_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enve_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recieved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bal_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
