# Generated by Django 5.2.5 on 2025-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_press_name_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
