# Generated by Django 5.2.5 on 2025-08-19 12:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_login_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='raw_password',
        ),
        migrations.RemoveField(
            model_name='deleteduser',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='original_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='unique_deleted_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
