# Generated by Django 5.2.5 on 2025-08-19 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_deleteduser_raw_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='email',
            field=models.EmailField(default='deleted@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='first_name',
            field=models.CharField(default='Deleted', max_length=30),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='last_name',
            field=models.CharField(default='User', max_length=150),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='original_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='username',
            field=models.CharField(default='deleted_user', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
