# Generated by Django 5.2.5 on 2025-08-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_deleteduser_date_joined_and_more'),
    ]

    operations = [
    ]
