# Generated by Django 5.2.5 on 2025-08-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250819_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='press_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
