# Generated by Django 5.2.5 on 2025-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deleteduser_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login_link',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Short Credit', 'Short Credit'), ('Temporary', 'Temporary'), ('Received', 'Received')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Accountant', 'Accountant'), ('Operator', 'Operator'), ('Helper', 'Helper')], max_length=20, null=True),
        ),
    ]
